spring:
  application:
    name: ProductService
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3301/productservicedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
  sql:
    init:
      mode: never

    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 dakika
      cache-null-values: false
      key-prefix: "product:"
      use-key-prefix: true
  data:
    redis:
      host: localhost
      port: 6379
      password:  # Şifre varsa
      database: 0
      # timeout deprecated, yerine connection-timeout kullan
      connection-timeout: 2000ms
      # Yeni timeout ayarları
      timeout: 2000ms  # Command timeout
      lettuce:
        pool:
          max-active: 8      # Maksimum aktif bağlantı
          max-idle: 8        # Maksimum boşta bağlantı
          min-idle: 0        # Minimum boşta bağlantı
          max-wait: -1ms     # Bağlantı bekleme süresi
          time-between-eviction-runs: 30000ms  # Eviction çalışma aralığı
  # elasticsearch:
  #     rest:
  #       uris: http://localhost:9200
  #       connection-timeout: 5000
  #       read-timeout: 5000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 1.0
server:
  port: 8088

eureka:
   instance:
     preferIpAddress: true
   client:
     fetchRegistry: true
     registerWithEureka: true
     serviceUrl:
      defaultZone: http://localhost:8070/eureka/

aws:
  s3:
    bucket: smartspirit-ecommerce-photos-eu-central
    cloudfront-url: https://d2asj86e04rqv6.cloudfront.net
    region: eu-central-1 # bucket'ı hangi bölgede oluşturduysan
    access-key: AKIAS66UDDNEULUZCOVN
    secret-key: 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


# elasticsearch:
#   index:
#     category: categories
#     product: products
#   cluster:
#     name: elasticsearch
#     nodes: localhost:9200


