server:
  port: 8086
spring:
  application:
    name: PaymentService
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3305/paymentservicedb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true


iyzico:
  api-key: sandbox-kaRR3Llj55mtPTPgxRgjRO9EG3fmPijW
  secret-key: sandbox-8mrerFZWc60bveHsnJxxEOKe0GGfBMRQ
  base-url: https://sandbox-api.iyzipay.com